INSERT INTO raw.user_raw
VALUES 
(
  %(user_id)s,
  %(name)s,
  %(review_count)s,
  %(yelping_since)s,
  %(friends)s,
  %(useful)s,
  %(funny)s,
  %(cool)s,
  %(fans)s,
  %(elite)s,
  %(average_stars)s,
  %(compliment_hot)s,
  %(compliment_more)s,
  %(compliment_profile)s,
  %(compliment_cute)s,
  %(compliment_list)s,
  %(compliment_note)s,
  %(compliment_plain)s,
  %(compliment_cool)s,
  %(compliment_funny)s,
  %(compliment_writer)s,
  %(compliment_photos)s
);
